(() => {
  const W=13,H=11,ROOM_W=20,ROOM_H=1,KEY='komorebi-territory-demo-v1',WORLD_START=Date.now(),STEP_MS=1250;
  const items=[
    {id:'flower',name:'野の花の花壇',icon:'🌼',cost:30,bonus:8,desc:'家の収入が少し増える',group:'はじまりの道具'},
    {id:'lamp',name:'きのこのランプ',icon:'🍄',cost:55,bonus:15,desc:'家の収入が増える',group:'はじまりの道具'},
    {id:'cottage',name:'ちいさな小屋',icon:'🏡',cost:100,bonus:25,desc:'家の収入が大きく増える',group:'はじまりの道具'},
    {id:'fence',name:'木の柵',icon:'🪵',cost:45,bonus:0,desc:'家のかざり',group:'はじまりの道具'},
    {id:'moss-wall',name:'苔むす森の壁',icon:'🌿',cost:180,bonus:5,desc:'森色の壁紙・収入 +5%',kind:'wall',group:'森のよりみち'},
    {id:'fern',name:'大きなシダの鉢',icon:'🪴',cost:95,bonus:12,desc:'葉っぱの家具・収入 +12%',group:'森のよりみち'},
    {id:'mushroom-chair',name:'きのこの腰かけ',icon:'🍄',cost:120,bonus:14,desc:'きのこ型の椅子・収入 +14%',group:'森のよりみち'},
    {id:'wave-wall',name:'波音の青い壁',icon:'🌊',cost:220,bonus:6,desc:'海辺色の壁紙・収入 +6%',kind:'wall',group:'釣り人の小屋'},
    {id:'fishing-lantern',name:'釣り人の灯り',icon:'🏮',cost:250,bonus:18,desc:'夜釣りを照らす吊り灯・収入 +18%',group:'釣り人の小屋'},
    {id:'fish-mobile',name:'魚影のモビール',icon:'🐟',cost:185,bonus:10,desc:'窓辺に泳ぐ魚飾り・収入 +10%',group:'釣り人の小屋'},
    {id:'star-wall',name:'星降る夜の壁',icon:'🌌',cost:280,bonus:7,desc:'夜空色の壁紙・収入 +7%',kind:'wall',group:'星明かりの寝室'},
    {id:'moon-lamp',name:'月あかりランプ',icon:'🌙',cost:340,bonus:24,desc:'月型のやさしい灯り・収入 +24%',group:'星明かりの寝室'},
    {id:'star-cushion',name:'星くずクッション',icon:'⭐',cost:200,bonus:13,desc:'星形のふかふか家具・収入 +13%',group:'星明かりの寝室'},
    {id:'bookcase',name:'冒険者の本棚',icon:'📚',cost:130,bonus:10,desc:'読みかけの本を並べる・収入 +10%',group:'旅の思い出'},
    {id:'cushion',name:'森色クッション',icon:'🛋️',cost:115,bonus:9,desc:'くつろぎの小物・収入 +9%',group:'旅の思い出'},
    {id:'photo-frame',name:'旅の写真立て',icon:'🖼️',cost:160,bonus:12,desc:'冒険の景色を飾る・収入 +12%',group:'旅の思い出'},
    {id:'aqua-bowl',name:'小さな水槽',icon:'🐠',cost:230,bonus:17,desc:'ゆらゆら泳ぐ魚・収入 +17%',group:'旅の思い出'},
    {id:'bait-shelf',name:'釣り道具の棚',icon:'🎣',cost:175,bonus:11,desc:'釣り道具をすっきり収納・収入 +11%',group:'旅の思い出'},
    {id:'wind-chime',name:'木もれ日の風鈴',icon:'🎐',cost:145,bonus:10,desc:'窓辺で鳴る飾り・収入 +10%',group:'旅の思い出'},
    {id:'scout-boots',name:'斥候のブーツ',icon:'🥾',cost:180,bonus:0,kind:'gear',role:'attack',desc:'占領にかかる時間を短縮',group:'攻撃装備'},
    {id:'battering-ram',name:'小型破城槌',icon:'🪓',cost:290,bonus:0,kind:'gear',role:'attack',desc:'敵の領地を攻める時間を短縮',group:'攻撃装備'},
    {id:'war-banner',name:'開拓団の軍旗',icon:'🚩',cost:360,bonus:0,kind:'gear',role:'attack',desc:'攻撃装備の効果を底上げ',group:'攻撃装備'},
    {id:'watchtower',name:'見張り塔',icon:'🗼',cost:210,bonus:0,kind:'gear',role:'defense',desc:'コンピューターの攻撃を遅らせる',group:'防衛装置'},
    {id:'thorn-trap',name:'いばらのわな',icon:'🪤',cost:190,bonus:0,kind:'gear',role:'defense',desc:'攻めてきた相手を足止め',group:'防衛装置'},
    {id:'ward-crystal',name:'守護の結晶',icon:'💎',cost:320,bonus:0,kind:'gear',role:'defense',desc:'領地を守る時間を延ばす',group:'防衛装置'}
  ];
  const ECONOMY_SCALE=32;
  for(const item of items)item.cost*=ECONOMY_SCALE;
  const sets=[{name:'森のよりみちセット',icon:'🌳',ids:['moss-wall','fern','mushroom-chair']},{name:'釣り人の小屋セット',icon:'🎣',ids:['wave-wall','fishing-lantern','fish-mobile']},{name:'星明かりの寝室セット',icon:'🌙',ids:['star-wall','moon-lamp','star-cushion']}];
  const initial=()=>({name:'',nameChosen:false,points:80,morale:3,lastTick:Date.now(),decor:[],inventory:[],wallStyles:{},wallStyle:'',lands:['6,5'],home:'6,5',pos:'6,5',ownedSince:{'6,5':Date.now()},past:['6,5'],attacks:{},attempts:{},selected:'6,5',occupy:null,travel:null,inside:false,houseSlot:'19,0',pendingItem:null,pendingMove:null,limitedShop:null,limitedOpen:false,nextShopAt:Date.now()+55000+Math.random()*45000,log:['冒険者ギルドに登録して、世界へ出発しよう。']});
  const savedState=localStorage.getItem(KEY);let isNewPlayer=!savedState;
  let state;try{state={...initial(),...JSON.parse(savedState||'{}')}}catch{state=initial();isNewPlayer=true}
  if((Number(state.economyVersion)||0)<1){state.points=(Number(state.points)||80)*ECONOMY_SCALE;state.economyVersion=1;state.lastTick=Date.now()}
  if(!Array.isArray(state.inventory))state.inventory=[];
  if(!Array.isArray(state.decor))state.decor=[];
  if(state.occupy?.type==='wild'){state.occupy=null;state.log=['空き地は現地で購入する方式になりました。',...(state.log||[])].slice(0,6)}
  state.wallStyles=state.wallStyles||{};
  state.gear=state.gear||{};
  state.inventory=state.inventory.map((entry,i)=>typeof entry==='string'?{uid:`inventory-old-${i}`,id:entry,lvl:0}:{...entry,uid:entry.uid||`inventory-old-${i}`,lvl:Number(entry.lvl)||0});
  state.decor=state.decor.map((entry,i)=>typeof entry==='string'?{uid:`decor-old-${i}`,id:entry,lvl:0}:{...entry,lvl:Number(entry.lvl)||0});
  state.limitedShop=state.limitedShop||null;state.limitedOpen=!!state.limitedOpen;state.nextShopAt=Number(state.nextShopAt)||Date.now()+60000;
  let decorSeq=0;
  const occupiedRoomSlots=new Set();
  state.decor=state.decor.map((d,i)=>{const entry=typeof d==='string'?{uid:`old-${i}`,id:d,slot:`${i%ROOM_W},0`}:{...d,uid:d.uid||`old-${i}`,slot:d.slot||`${i%ROOM_W},0`};let [x,y]=entry.slot.split(',').map(Number);if(!Number.isInteger(x)||x<0||x>=ROOM_W||y!==0||occupiedRoomSlots.has(`${x},0`)){x=Array.from({length:ROOM_W},(_,n)=>n).find(n=>!occupiedRoomSlots.has(`${n},0`))??(i%ROOM_W);entry.slot=`${x},0`}occupiedRoomSlots.add(entry.slot);return entry});
  if(state.pendingItem&&!state.inventory.some(entry=>entry.uid===state.pendingItem))state.pendingItem=state.inventory.find(entry=>entry.id===state.pendingItem)?.uid||null;
  {const x=Number(String(state.houseSlot||`${ROOM_W-1},0`).split(',')[0]);state.houseSlot=`${Number.isInteger(x)&&x>=0?x%ROOM_W:ROOM_W-1},0`}
  if(state.name==='こもれびさん'&&!state.nameChosen){state.name='';state.nameChosen=false}
  const $=id=>document.getElementById(id),key=(x,y)=>`${x},${y}`,xy=k=>k.split(',').map(Number),has=k=>state.lands.includes(k),itemFor=id=>items.find(i=>i.id===id);
  const map=$('map'),cells=[];let selected=state.selected||state.home;
  const water=new Set(['0,0','1,0','2,0','0,1','12,0','12,1','12,2','0,10','1,10','12,9','12,10','2,9','3,9']);
  const forest=new Set(['3,2','4,2','5,2','9,1','10,1','10,2','2,7','3,7','9,8','10,8','11,8','7,1','8,1','1,4','11,5']);
  const landmarks={'9,3':'🪨','3,5':'🌳','8,7':'🪷','5,8':'🌳','10,5':'🪨'},cellData={};
  for(let y=0;y<H;y++)for(let x=0;x<W;x++){
    const k=key(x,y),el=document.createElement('button');el.className='cell';el.type='button';el.setAttribute('role','gridcell');el.dataset.key=k;
    const hash=(x*37+y*71+x*y*13)%17,type=water.has(k)?'water':forest.has(k)?'forest':'path';cellData[k]={type,wild:!water.has(k)&&!forest.has(k)&&hash===0,icon:landmarks[k]||''};
    el.addEventListener('click',()=>clickCell(k));map.appendChild(el);cells.push(el);
  }
  const botDefaults=[{id:'mugi',name:'@mugi',icon:'🤖',lands:['8,4','9,4','10,4']},{id:'ao',name:'@ao',icon:'🛡️',lands:['3,4','3,3']},{id:'sora',name:'@sora',icon:'⚔️',lands:['10,2','11,2']}];
  state.computers=Array.isArray(state.computers)?state.computers:botDefaults.map(bot=>({...bot,nextActionAt:Date.now()+18000+Math.random()*26000,action:null}));
  if(isNewPlayer){const near=(a,b)=>{const [x,y]=xy(a),[u,v]=xy(b);return Math.abs(x-u)+Math.abs(y-v)};let candidates=Object.keys(cellData).filter(k=>!water.has(k)&&!forest.has(k)&&state.computers.every(bot=>bot.lands.every(enemy=>near(k,enemy)>=4)));if(!candidates.length)candidates=Object.keys(cellData).filter(k=>!water.has(k)&&state.computers.every(bot=>bot.lands.every(enemy=>near(k,enemy)>=2)));const spawn=candidates[Math.floor(Math.random()*candidates.length)]||'6,5';state.home=state.pos=state.selected=selected=spawn;state.lands=[spawn];state.past=[spawn];state.ownedSince={[spawn]:Date.now()}}
  for(const bot of state.computers){bot.lands=(Array.isArray(bot.lands)?bot.lands:[]).filter(k=>!state.lands.includes(k));bot.nextActionAt=Number(bot.nextActionAt)||Date.now()+25000;bot.action=bot.action||null;bot.icon=bot.icon||'🤖';bot.position=bot.position||bot.lands[0]||null}
  const demoOthers={},demoReclaim=new Set(['8,4','9,4']),staticLands=new Set();
  for(const bot of state.computers)for(const land of bot.lands){if(!has(land)){demoOthers[land]=bot.name;staticLands.add(land)}}
  function save(){state.selected=selected;localStorage.setItem(KEY,JSON.stringify(state))}
  function xLabel(k){const [x,y]=xy(k);return `マス ${x+1},${y+1}`}
  function ownedCount(){return state.lands.length}
  function itemCount(id){const item=itemFor(id);return item?.kind==='wall'?(Number(state.wallStyles[id])||0):item?.kind==='gear'?(Number(state.gear[id]?.count)||0):state.decor.filter(d=>d.id===id).length+state.inventory.filter(d=>d.id===id).length}
  function gearLevel(id){return Number(state.gear[id]?.level)||0}
  function placedBonus(){return state.decor.reduce((a,d)=>a+(itemFor(d.id)?.bonus||0)*(1+(Number(d.lvl)||0)*.5),0)+items.filter(i=>i.kind==='wall').reduce((a,i)=>a+(state.wallStyle===i.id?i.bonus*(Number(state.wallStyles[i.id])||0):0),0)}
  function perMinute(){return ownedCount()*6*ECONOMY_SCALE*(1+Math.min(5,placedBonus()/100))}
  function upgradePrice(item,level){const scaled=Math.ceil(item.cost*.7*Math.pow(level+1,1.35)),inflationFloor=Math.max(Math.ceil(item.cost*.7),Math.floor(state.points*.12));return Math.min(scaled,inflationFloor)}
  function makeInventoryItem(id){return{uid:`item-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,id,lvl:0}}
  function log(msg){state.log.unshift(msg);state.log=state.log.slice(0,6);if(/あなたの領地を占領した|敵の土地を占領した|土地を取り返した/.test(msg))announce(msg)}
  let alertTimer=0;
  function announce(msg){const box=$('worldAlert');$('worldAlertText').textContent=msg;box.classList.remove('hidden');box.classList.remove('alert-flash');void box.offsetWidth;box.classList.add('alert-flash');clearTimeout(alertTimer);alertTimer=setTimeout(()=>box.classList.add('hidden'),9000)}
  function ownedElse(k){return (staticLands.has(k)||demoReclaim.has(k))&&!has(k)}
  function targetType(k){if(has(k))return 'own';if(ownedElse(k))return demoReclaim.has(k)?'reclaim':'raid';return cellData[k]?.wild?'wild':'path'}
  function playerPresent(k){return document.visibilityState==='visible'&&!state.travel&&!state.inside&&state.pos===k}
  function defendedInPerson(k){return playerPresent(k)||state.computers.some(bot=>bot.position===k&&bot.lands.includes(k))}
  function durationFor(k,type){if(type==='wild')return 30;const base=type==='reclaim'?15:Math.min(240,60+(state.attempts[k]||0)*30),bonus=items.filter(i=>i.kind==='gear'&&i.role==='attack').reduce((n,i)=>n+itemCount(i.id)*(.04+gearLevel(i.id)*.015)*(i.id==='war-banner'?1.4:1),0),guard=type==='raid'&&defendedInPerson(k)?4:1;return Math.max(type==='reclaim'?8:20,Math.ceil(base*guard/(1+bonus)))}
  function drawMap(){for(const el of cells){const k=el.dataset.key,info=cellData[k],mine=has(k),other=ownedElse(k),player=state.pos===k,limited=state.limitedShop?.key===k&&state.limitedShop.closesAt>Date.now(),bot=state.computers.find(b=>b.lands.includes(k)),underAttack=state.computers.some(b=>b.action?.target===k);el.className=`cell ${info.type}${mine?' yours':''}${other?' other':''}${other&&demoReclaim.has(k)?' reclaim':''}${selected===k?' selected':''}${player?' player':''}${k===state.home?' home':''}${limited?' limited-shop':''}${underAttack?' bot-attacking':''}`;el.innerHTML='';const icon=document.createElement('span');icon.className='cell-icon';icon.textContent=mine?(k===state.home?'🏠':'🌿'):(other?(bot?.icon||'🏡'):(info.wild?'✨':info.icon));el.appendChild(icon);if(underAttack){const mark=document.createElement('span');mark.className='land-mark';mark.textContent='⚔️';el.appendChild(mark)}else if(mine&&k!==state.home){const mark=document.createElement('span');mark.className='land-mark';mark.textContent='✦';el.appendChild(mark)}if(limited){const badge=document.createElement('span');badge.className='limited-shop-mark';badge.textContent='🛒';el.appendChild(badge)}el.setAttribute('aria-label',`${xLabel(k)}${limited?' 限定ショップ営業中':mine?' あなたの土地':other?' '+demoOthers[k]+'の土地'+(underAttack?'・CPUが侵攻中':''):info.wild?' 無人地':''}`)}}
  function findPath(start,goal){const q=[start],prev=new Map([[start,null]]);for(let i=0;i<q.length;i++){const here=q[i];if(here===goal)break;const [x,y]=xy(here);for(const [nx,ny] of [[x,y-1],[x-1,y],[x,y+1],[x+1,y]]){const next=key(nx,ny);if(nx<0||ny<0||nx>=W||ny>=H||water.has(next)||prev.has(next))continue;prev.set(next,here);q.push(next)}}if(!prev.has(goal))return null;const path=[];for(let at=goal;at&&at!==start;at=prev.get(at))path.unshift(at);return path}
  function clickCell(k){if(state.inside)return;selected=k;$('targetPanel').open=true;if(k===state.pos){render();save();return}beginTravel(k)}
  function beginTravel(goal){const path=findPath(state.pos,goal);if(!path){log('その場所へ続く道が見つからない。');render();save();return}if(!path.length){onArrive(goal);render();return}if(state.occupy)cancelOccupation('移動を始めたので占領を中断した。気力を少し消耗した。');state.travel={goal,path,cursor:0,startedAt:Date.now(),stepMs:STEP_MS};state.inside=false;state.limitedOpen=false;log(`${xLabel(goal)}へ向けて歩き始めた。`);render();save()}
  function tickTravel(now){const t=state.travel;if(!t)return;const due=Math.min(t.path.length,Math.floor((now-t.startedAt)/t.stepMs));while(t.cursor<due){const next=t.path[t.cursor++];state.pos=next}if(t.cursor>=t.path.length){state.pos=t.goal;state.travel=null;onArrive(t.goal)}}
  function onArrive(k){selected=k;$('targetPanel').open=true;if(state.limitedShop?.key===k&&state.limitedShop.closesAt>Date.now()){state.limitedOpen=true;log('限定ショップに到着！閉店までに品物を見ていこう。');return}const type=targetType(k);if(type==='own'){log(k===state.home?'家に帰ってきた。':'自分の領地に到着。');return}if(type==='path'||type==='wild'){log(`${xLabel(k)}に到着。空き地ならここで購入できます。`);return}if(type==='reclaim'||type==='raid'){if(state.morale<.2){log('気力が足りない。家で休もう。');return}startOccupation(k,type)}}
  function startOccupation(k,type){const required=durationFor(k,type);state.occupy={key:k,type,required,startedAt:Date.now(),progress:0};log(type==='wild'?'無人地の開拓を始めた。':type==='reclaim'?'昔の自分の土地を取り返し始めた。':'敵の土地へ攻め込んだ。')}
  function cancelOccupation(message='占領を中断した。気力を少し消耗した。'){const o=state.occupy;if(o&&(o.type==='raid'||o.type==='reclaim')){state.attempts[o.key]=(state.attempts[o.key]||0)+1;state.morale=Math.max(0,state.morale-.5)}state.occupy=null;log(message)}
  function tickComputers(now){for(const bot of state.computers){if(bot.action){if(now-bot.action.startedAt<bot.action.duration*1000)continue;const k=bot.action.target,wasMine=has(k),previous=state.computers.find(other=>other!==bot&&other.lands.includes(k));if(wasMine&&playerPresent(k)){bot.action=null;bot.nextActionAt=now+18000;log(`${bot.name}は現地での防衛に阻まれ、${xLabel(k)}から撤退した。`);continue}if(wasMine){state.lands=state.lands.filter(land=>land!==k);state.ownedSince&&delete state.ownedSince[k];if(!state.past.includes(k))state.past.push(k);demoReclaim.add(k);log(`${bot.name}があなたの領地を占領した！現地に行けば奪還できる。`)}if(previous)previous.lands=previous.lands.filter(land=>land!==k);bot.lands.push(k);bot.position=k;demoOthers[k]=bot.name;staticLands.add(k);demoReclaim.delete(k);if(!wasMine){const message=previous?`${bot.name}が${previous.name}の領地を占領！${xLabel(k)}の持ち主が変わりました。`:`${bot.name}が新しい領地を獲得！${xLabel(k)}がCPU領地になりました。`;log(message);announce(message)}bot.action=null;bot.nextActionAt=now+35000+Math.random()*45000;continue}if(now<bot.nextActionAt)continue;const frontier=new Set();for(const land of bot.lands){const [x,y]=xy(land);for(const [nx,ny] of [[x,y-1],[x-1,y],[x,y+1],[x+1,y]]){const k=key(nx,ny);if(nx>=0&&ny>=0&&nx<W&&ny<H&&!water.has(k)&&!bot.lands.includes(k))frontier.add(k)}}let choices=[...frontier].filter(k=>!state.computers.some(other=>other!==bot&&other.action?.target===k)&&!(has(k)&&playerPresent(k)));if(!choices.length)choices=Object.keys(cellData).filter(k=>!water.has(k)&&!bot.lands.includes(k)&&!state.computers.some(other=>other!==bot&&other.action?.target===k)&&!(has(k)&&playerPresent(k)));if(!choices.length){bot.nextActionAt=now+30000;continue}const target=choices[Math.floor(Math.random()*choices.length)],isPlayer=has(target),isOwned=ownedElse(target);let duration=isPlayer?45:isOwned?34:18;if(isPlayer){const defense=items.filter(i=>i.kind==='gear'&&i.role==='defense').reduce((n,i)=>n+itemCount(i.id)*(.22+gearLevel(i.id)*.08),0);duration=Math.ceil(duration*(1+defense))}bot.action={target,startedAt:now,duration};log(`${bot.name}が${xLabel(target)}へ侵攻を開始。約${duration}秒で決着する。`);bot.nextActionAt=now+duration*1000}}
  function finishOccupation(){const o=state.occupy;if(!o)return;const k=o.key;if(o.type==='wild'){state.lands.push(k);state.past.push(k);state.ownedSince[k]=Date.now();state.morale=Math.min(3,state.morale+1.5);log('無人地を開拓した！ここから収入が生まれる。')}else{if(staticLands.has(k)){staticLands.delete(k);delete demoOthers[k];for(const bot of state.computers)bot.lands=bot.lands.filter(land=>land!==k)}demoReclaim.delete(k);if(!has(k))state.lands.push(k);state.ownedSince[k]=Date.now();state.attempts[k]=0;state.morale=Math.min(3,state.morale+1.5);state.attacks[k]=(state.attacks[k]||0)+1;log(o.type==='reclaim'?'土地を取り返した！領地の色があなたの色に変わった。':'敵の土地を占領した！領地の色があなたの色に変わった。')}state.occupy=null;selected=k}
  function tileName(k,type){return type==='own'?(k===state.home?'はじまりの家':'あなたの領地'):type==='raid'?`${demoOthers[k]||'ほかの人'}の領地`:type==='reclaim'?'以前のあなたの領地':type==='wild'||type==='path'?'空き地':'草地'}
  function actionButtons(){const wrap=$('tileActions');wrap.innerHTML='';const k=selected,typ=targetType(k);$('tileTitle').textContent=tileName(k,typ);$('tileBadge').textContent=typ==='own'?'所有中':typ==='wild'?'購入できる空き地':typ==='reclaim'?'奪還可能':typ==='raid'?'敵の領地':'購入できる空き地';$('tileDescription').textContent=typ==='own'?(k===state.home?'あなたの家。中に入って家具を置き、飾りボーナスを育てよう。':'あなたが所有する領地。時間とともにポイントを生みます。'):typ==='wild'||typ==='path'?`空いている土地。現地に着いてから${70*ECONOMY_SCALE}ptで購入できます。`:typ==='reclaim'?'以前あなたが持っていた領地。滞在すると取り返せます。':typ==='raid'?`持ち主がいる領地。占領には${durationFor(k,'raid')}秒必要。持ち主が現地にいる間は通常の4倍かかり、攻めるたびに時間が延びます。`:'草地を歩いて探索できます。';
    if(k!==state.pos){const b=document.createElement('button');b.textContent=state.travel?.goal===k?'目的地に設定中…':'ここへ向かう';b.disabled=!!state.travel||!!state.occupy;b.addEventListener('click',()=>beginTravel(k));wrap.appendChild(b)}
    if((typ==='path'||typ==='wild')&&k===state.pos&&!state.travel&&!state.inside){const buy=document.createElement('button');buy.textContent=`この土地を購入 · ${70*ECONOMY_SCALE}pt`;buy.disabled=state.points<70*ECONOMY_SCALE;buy.addEventListener('click',()=>buyPlotAt(k));wrap.appendChild(buy)}
    if(k===state.home&&state.pos===state.home&&!state.travel&&!state.inside){const b=document.createElement('button');b.textContent='家の中を見る';b.addEventListener('click',enterHome);wrap.appendChild(b)}
    if(state.limitedShop?.key===k&&state.limitedShop.closesAt>Date.now()&&state.pos===k&&!state.travel&&!state.inside){const b=document.createElement('button');b.textContent='🛒 限定ショップを開く';b.addEventListener('click',()=>{state.limitedOpen=true;render();save()});wrap.appendChild(b)}
  }
  function renderHouse(){const floor=$('houseFloor');floor.classList.remove('wall-style-moss-wall','wall-style-wave-wall','wall-style-star-wall');if(state.wallStyle)floor.classList.add(`wall-style-${state.wallStyle}`);floor.innerHTML='';for(let y=0;y<ROOM_H;y++)for(let x=0;x<ROOM_W;x++){const slot=key(x,y),button=document.createElement('button');button.type='button';button.className='room-tile';button.dataset.slot=slot;const furniture=state.decor.find(d=>d.slot===slot),isDoor=x===0;button.classList.toggle('occupied',!!furniture);button.classList.toggle('slot-selected',state.houseSlot===slot);button.setAttribute('role','gridcell');button.setAttribute('aria-label',furniture?`${itemFor(furniture.id)?.name||'家具'} Lv.${furniture.lvl||0}、床の位置${x+1}`:`空き床、位置${x+1}`);button.innerHTML=`<span class="${isDoor?'room-door':furniture?`room-piece piece-${furniture.id}`:''}" aria-hidden="true">${furniture&&!['flower','lamp','cottage','fence'].includes(furniture.id)?itemFor(furniture.id)?.icon||'🪑':''}</span>${state.inside&&slot===`${ROOM_W-1},0`?'<i class="room-player">🧙</i>':''}`;button.addEventListener('click',()=>clickRoomSlot(slot));floor.appendChild(button)}
    const list=$('inventoryList'),furnishings=state.inventory.filter(entry=>{const item=itemFor(entry.id);return item&&item.kind!=='wall'&&item.kind!=='gear'});list.innerHTML='';if(!furnishings.length){list.innerHTML='<span class="empty-inventory">持ち物は空です。ショップで家具を探そう。</span>'}else furnishings.forEach(entry=>{const item=itemFor(entry.id);const b=document.createElement('button');b.type='button';b.className='inventory-item';b.classList.toggle('chosen',state.pendingItem===entry.uid);b.innerHTML=`<span>${item.icon}</span><span>${item.name} · Lv.${entry.lvl||0}</span>`;b.addEventListener('click',()=>{state.pendingItem=entry.uid;state.pendingMove=null;$('houseMessage').textContent=`${item.name}を置く床を選んでください。`;renderHouse()});list.appendChild(b)});
    if(state.houseSlot){const placed=state.decor.find(d=>d.slot===state.houseSlot);if(placed){const b=document.createElement('button');b.type='button';b.className='inventory-item remove-item';b.textContent=`🧺 ${itemFor(placed.id)?.name||'家具'} Lv.${placed.lvl||0}を片づける`;b.addEventListener('click',()=>{state.inventory.push(placed);state.decor=state.decor.filter(d=>d.uid!==placed.uid);state.pendingMove=null;log('家具を持ち物に戻した。');render();save()});list.appendChild(b)}}
    const pending=state.inventory.find(entry=>entry.uid===state.pendingItem);if(pending)$('houseMessage').textContent=`${itemFor(pending.id)?.name||'家具'}を置く床を選んでください。`;else if(state.pendingMove)$('houseMessage').textContent='移動先の空いている床を選んでください。';else $('houseMessage').textContent='家具を選んでから、床のマスを選ぶと置けるよ。';
  }
  function clickRoomSlot(slot){state.houseSlot=slot;const existing=state.decor.find(d=>d.slot===slot);if(state.pendingItem){if(existing){log('その床にはすでに家具が置いてある。');renderHouse();return}const i=state.inventory.findIndex(entry=>entry.uid===state.pendingItem);if(i>=0){const piece=state.inventory.splice(i,1)[0];piece.slot=slot;state.decor.push(piece);log(`${itemFor(piece.id)?.name||'家具'}を家に飾った。`)}state.pendingItem=null}else if(existing){state.pendingMove=existing.uid;state.pendingItem=null;$('houseMessage').textContent='移動先の空いている床を選んでください。'}else if(state.pendingMove){const piece=state.decor.find(d=>d.uid===state.pendingMove);if(piece){piece.slot=slot;log(`${itemFor(piece.id)?.name||'家具'}を移動した。`)}state.pendingMove=null}else $('houseMessage').textContent='空いている床です。家具を選ぶとここに置けます。';render();save()}
  function enterHome(){if(state.pos!==state.home||state.travel)return;state.inside=!state.inside;state.pendingItem=null;state.pendingMove=null;if(state.inside){log('はじまりの家に入った。家具を飾ってみよう。')}else log('家を出て、原っぱへ戻った。');render();save()}
  function buyPlotAt(k){if(k!==state.pos||state.travel||state.inside||state.points<70*ECONOMY_SCALE||has(k)||ownedElse(k)||water.has(k))return;state.points-=70*ECONOMY_SCALE;state.lands.push(k);state.past.push(k);state.ownedSince[k]=Date.now();selected=k;log(`${xLabel(k)}を${70*ECONOMY_SCALE}ptで購入した。ここから収入が生まれる。`);render();save()}
  function buyItem(item,price){if(state.points<price)return false;if(item.kind==='wall'){const level=Number(state.wallStyles[item.id])||0;if(level>=3)return false;state.points-=price;state.wallStyles[item.id]=level+1;state.wallStyle=item.id;log(`${item.name}を張った。壁紙 Lv.${level+1}になった。`)}else if(item.kind==='gear'){if(itemCount(item.id)>=3)return false;state.points-=price;state.gear[item.id]={count:itemCount(item.id)+1,level:gearLevel(item.id)};log(`${item.name}を設置した。装備数 ${itemCount(item.id)}/3。`)}else{if(itemCount(item.id)>=3)return false;state.points-=price;const piece=makeInventoryItem(item.id);state.inventory.push(piece);if(state.pos===state.home){state.pendingItem=piece.uid;state.inside=true}log(`${item.name}を買った。家に置いて育てよう。`)}render();save();return true}
  function upgradeItem(item){if(item.kind==='wall'){const level=Number(state.wallStyles[item.id])||0;if(level<=0||level>=3)return;const price=upgradePrice(item,level);if(state.points<price)return;state.points-=price;state.wallStyles[item.id]=level+1;state.wallStyle=item.id;log(`${item.name}を強化した。壁紙 Lv.${level+1}！`)}else if(item.kind==='gear'){const gear=state.gear[item.id];if(!gear||gear.count<=0)return;const level=gearLevel(item.id),price=upgradePrice(item,level);if(state.points<price)return;state.points-=price;gear.level=level+1;log(`${item.name}を強化した。Lv.${gear.level}！`)}else{const owned=[...state.inventory,...state.decor].filter(piece=>piece.id===item.id).sort((a,b)=>(a.lvl||0)-(b.lvl||0));const piece=owned[0];if(!piece)return;const level=Number(piece.lvl)||0,price=upgradePrice(item,level);if(state.points<price)return;state.points-=price;piece.lvl=level+1;log(`${item.name}を強化した。Lv.${piece.lvl}！`)}render();save()}
  function buySet(set){const contents=set.ids.map(itemFor),canBuy=contents.every(item=>itemCount(item.id)<3);const price=Math.ceil(contents.reduce((sum,item)=>sum+item.cost,0)*.82);if(!canBuy||state.points<price)return;state.points-=price;for(const item of contents){if(item.kind==='wall'){state.wallStyles[item.id]=(Number(state.wallStyles[item.id])||0)+1;state.wallStyle=item.id}else state.inventory.push(makeInventoryItem(item.id))}log(`${set.name}を購入！3つの品を手に入れた。`);render();save()}
  function productCard(item,container,limited=null){const card=document.createElement('article');card.className='shop-item';const count=itemCount(item.id),owned=item.kind==='wall'?count:item.kind==='gear'?count:[...state.inventory,...state.decor].filter(piece=>piece.id===item.id),lowest=item.kind==='wall'?count:item.kind==='gear'?gearLevel(item.id):(owned.length?Math.min(...owned.map(piece=>Number(piece.lvl)||0)):0),price=item.cost*(1+count*.25),upgrade=owned.length||item.kind==='wall'&&count>0,upgradeCost=upgradePrice(item,lowest);card.innerHTML=`<span class="emoji">${item.icon}</span><strong>${item.name}</strong><small>${item.desc}<br>所持 ${count}/3${item.kind==='wall'?` · Lv.${count}`:upgrade?` · 強化対象 Lv.${lowest}`:''}</small>`;
    const buy=document.createElement('button');buy.textContent=limited?`${limited.price} pt · 限定品購入`:item.kind==='wall'?count>=3?'最大強化':`${Math.ceil(price)} pt · 壁紙を強化 (${count}/3)`:count>=3?'所持上限 · 強化は可能':`${Math.ceil(price)} pt · 購入 (${count}/3)`;buy.disabled=limited?(limited.sold||count>=3||state.points<limited.price):(count>=3||state.points<price);buy.addEventListener('click',()=>{if(limited){if(limited.sold)return;if(buyItem(item,limited.price)){limited.sold=true;render();save()}}else buyItem(item,Math.ceil(price))});card.appendChild(buy);
    const up=document.createElement('button');up.className='upgrade-button';up.textContent=item.kind==='wall'?count===0?'先に壁紙を購入':count>=3?'強化上限':`${upgradeCost} pt · 壁紙強化`:`${upgradeCost} pt · 強化`;up.disabled=!upgrade||item.kind==='wall'&&count>=3||state.points<upgradeCost;up.addEventListener('click',()=>{if(limited){if(limited.sold)return;if(state.points<upgradeCost)return;upgradeItem(item);limited.sold=true;render();save()}else upgradeItem(item)});card.appendChild(up);container.appendChild(card)}
  function renderShop(){const setsBox=$('shopSets'),box=$('shopItems'),scrollTop=box.scrollTop;setsBox.innerHTML='';box.innerHTML='';for(const set of sets){const contents=set.ids.map(itemFor),price=Math.ceil(contents.reduce((sum,item)=>sum+item.cost,0)*.82),canBuy=contents.every(item=>itemCount(item.id)<3),card=document.createElement('article');card.className='bundle-card';card.innerHTML=`<span class="bundle-icon">${set.icon}</span><strong>${set.name}</strong><small>${contents.map(item=>item.name).join(' · ')}</small>`;const b=document.createElement('button');b.textContent=`${price} pt · 3点セット購入`;b.disabled=!canBuy||state.points<price;b.addEventListener('click',()=>buySet(set));card.appendChild(b);setsBox.appendChild(card)}
    let group='';for(const item of items){if(group!==item.group){group=item.group;const header=document.createElement('h3');header.className='catalog-group';header.textContent=group;box.appendChild(header)}productCard(item,box)}box.scrollTop=scrollTop;
  }
  function renderLimitedShop(){const panel=$('limitedShopPanel'),shop=state.limitedShop,open=!!(shop&&state.limitedOpen&&state.pos===shop.key&&!state.inside&&shop.closesAt>Date.now());panel.classList.toggle('hidden',!open);if(!open)return;$('limitedShopTimer').textContent=`閉店まで ${Math.max(0,Math.ceil((shop.closesAt-Date.now())/1000))}秒`;$('limitedShopOffers').innerHTML='';for(const offer of shop.stock){const item=itemFor(offer.id);if(!item)continue;const tag=document.createElement('span');tag.className='limited-discount';tag.textContent='本日限り';const card=document.createElement('article');card.className='limited-offer';card.append(tag);const host=document.createElement('div');productCard(item,host,offer);card.append(host);$('limitedShopOffers').appendChild(card)}}
  function updateLimitedShop(now){if(state.limitedShop&&now>=state.limitedShop.closesAt){state.limitedShop=null;state.limitedOpen=false;log('領地の限定ショップが閉店した。次の出店を待とう。')}if(!state.limitedShop&&now>=state.nextShopAt&&state.lands.length){const vacant=Object.keys(cellData).filter(k=>!water.has(k)&&!has(k)&&!ownedElse(k));if(!vacant.length){state.nextShopAt=now+30000;return}const key=vacant[Math.floor(Math.random()*vacant.length)],stock=items.slice().sort(()=>Math.random()-.5).slice(0,3).map(item=>({id:item.id,price:Math.ceil(item.cost*(.68+Math.random()*.16)),sold:false}));state.limitedShop={key,closesAt:now+120000,stock};state.limitedOpen=state.pos===key&&!state.travel&&!state.inside;state.nextShopAt=now+150000+Math.random()*240000;log(`${xLabel(key)}に限定ショップが開店！閉店まであと2分。`)} }
  function tick(){const now=Date.now(),elapsed=Math.max(0,now-(state.lastTick||now));if(elapsed>0){state.points+=perMinute()*elapsed/60000;state.lastTick=now;state.morale=Math.min(3,(state.morale||0)+elapsed/3600000*3)}updateLimitedShop(now);tickTravel(now);if(state.occupy){const occ=state.occupy;occ.progress=Math.max(0,Math.min(occ.required,(now-occ.startedAt)/1000));if(occ.progress>=occ.required)finishOccupation()}tickComputers(now);save();render()}
  function render(){drawMap();renderHouse();actionButtons();renderShop();renderLimitedShop();$('worldMapView').classList.toggle('hidden',state.inside);$('houseView').classList.toggle('hidden',!state.inside);$('homeBtn').textContent=state.inside?'🌲 外へ出る':'🏠 家に入る';$('homeBtn').disabled=state.pos!==state.home||!!state.travel;$('points').textContent=Math.floor(state.points).toLocaleString();$('income').textContent=`${perMinute().toFixed(1)} pt / 分`;$('bonus').textContent=`+${Math.min(500,placedBonus())}%`;$('moraleValue').textContent=`${Math.floor(state.morale)} / 3`;$('moraleBar').style.width=`${Math.max(0,state.morale)/3*100}%`;$('playerName').textContent=state.name||'冒険者';$('tileCount').textContent=ownedCount();$('playerCount').textContent=1+state.computers.length;$('locationLabel').textContent=state.inside?'はじまりの家の中':state.travel?`${xLabel(state.pos)}を移動中`:state.pos===state.home?'はじまりの家':xLabel(state.pos);const occ=state.occupy;$('occupation').classList.toggle('hidden',!occ);if(occ){$('targetPanel').open=true;const left=Math.max(0,occ.required-((Date.now()-occ.startedAt)/1000));$('occLabel').textContent=occ.type==='wild'?'未開拓地を開拓中…':occ.type==='reclaim'?'領地を奪還中…':'敵の領地を占領中…';$('occTime').textContent=`${Math.ceil(left)}秒`;$('occBar').style.width=`${Math.min(100,(Date.now()-occ.startedAt)/1000/occ.required*100)}%`}$('interruptBtn').onclick=()=>{cancelOccupation();render();save()};
    const t=state.travel;if(t){const elapsed=Math.max(0,Date.now()-t.startedAt),pct=Math.min(100,elapsed/(t.path.length*t.stepMs)*100),remaining=Math.max(0,Math.ceil((t.path.length*t.stepMs-elapsed)/1000));$('travelLabel').textContent=`${xLabel(t.goal)}へ向かっています · あと${remaining}秒`;$('travelBar').style.width=`${pct}%`;$('travelTrack').classList.add('moving')}else{$('travelLabel').textContent=occ?'占領ゲージが進行中':state.inside?'家具を配置できます':'行き先を選んでね';$('travelBar').style.width='0%';$('travelTrack').classList.remove('moving')}
    $('latestLog').textContent=state.log[0]||'記録を見る';$('eventLog').innerHTML=state.log.map(x=>`<li><time>✦</time>${escapeHtml(x)}</li>`).join('')}
  function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  $('homeBtn').addEventListener('click',enterHome);$('shopJumpBtn').addEventListener('click',()=>$('shopDialog').showModal());$('interruptBtn').addEventListener('click',()=>{cancelOccupation();render();save()});$('helpBtn').addEventListener('click',()=>$('helpDialog').showModal());document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
  $('renameBtn').addEventListener('click',()=>{$('nameInput').value=state.name||'';$('nameDialog').showModal()});$('nameDialog').querySelector('form').addEventListener('submit',e=>{const name=$('nameInput').value.trim().slice(0,12);if(!name){e.preventDefault();$('nameInput').focus();return}state.name=name;state.nameChosen=true;log(`${name}として冒険者登録した。`);render();save()});
  $('resetBtn').addEventListener('click',()=>{if(confirm('このブラウザーの試作データを最初からに戻す？')){localStorage.removeItem(KEY);location.reload()}});
  function clock(){const sec=Math.floor((Date.now()-WORLD_START)/1000);$('clock').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
  state.lastTick=state.lastTick||Date.now();render();clock();if(!state.nameChosen||!state.name)$('nameDialog').showModal();setInterval(()=>{tick();clock()},1000);
})();
