-- こもれび開拓団: 感想・報告の非公開保存テーブル
-- Supabase の SQL Editor で実行する想定。

create table if not exists public.feedback_reports (
  id bigint generated by default as identity primary key,
  client_report_id text not null unique,
  player_name text not null default '匿名の開拓者',
  report_type text not null check (report_type in ('impression','bug','request','other')),
  message text not null check (char_length(message) between 1 and 1200),
  client_time timestamptz,
  page_path text,
  game_label text,
  created_at timestamptz not null default now()
);

alter table public.feedback_reports enable row level security;

-- 公開ページからは投稿だけ許可。読み取り・更新・削除は許可しない。
drop policy if exists "public can submit feedback" on public.feedback_reports;
create policy "public can submit feedback"
on public.feedback_reports
for insert
to anon
with check (
  char_length(message) between 1 and 1200
  and report_type in ('impression','bug','request','other')
);

-- authenticated にも読み取りポリシーは作らない。
-- Supabase Dashboard / service_role / ChatGPT の接続済み Supabase 管理ツールからのみ確認する。

create index if not exists feedback_reports_created_at_idx
on public.feedback_reports (created_at desc);
